### PR TITLE
fix: fixed visible double registry

### PR DESCRIPTION
**Pull request by alsakhaev**
#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Bug fix
[ ] New feature
[ ] Documentation update
[ ] Add something to the core
[ ] Other, please explain:

#### Add a reference to a related issue if it exists

*issue:*

### CODE REVIEW

**Comment by Pasternag** [comment]
test101

**Comment by Pasternag** [comment]
test102

**Comment by Pasternag** [comment]
test103

**Comment by Gromazek** [comment]
test 7

**Comment by rezadeli** [comment]
Now it’s easy to send a tip on an issue or comment with Tipping NEAR Dapplet

**Comment by Bild96** [comment]
Now it’s easy to send a tip on an issue or comment with Tipping NEAR Dapplet

**Comment by alsakhaev** [comment]
Need to implement another UI

**Pull request closed without merging**
